num1 = int(input("Nhap vao so thu nhat : "))
num2 = int(input("Nhap vao so thu hai : "))
print(num1, '+', num2, '=', num1+num2)
print(num1, '-', num2, '=', num1-num2)
print(num1, '*', num2, '=', num1*num2)
print(num1, '//', num2, '=', num1//num2)
print(num1, '^', num2, '=', num1**num2)
